/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlightRecord extends org.jooq.impl.UpdatableRecordImpl<tech.codingclub.helix.tables.records.FlightRecord> implements org.jooq.Record5<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = -1772718174;

	/**
	 * Setter for <code>public.flight.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.flight.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.flight.from</code>.
	 */
	public void setFrom(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.flight.from</code>.
	 */
	public java.lang.String getFrom() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.flight.to</code>.
	 */
	public void setTo(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.flight.to</code>.
	 */
	public java.lang.String getTo() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.flight.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.flight.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.flight.cost</code>.
	 */
	public void setCost(java.lang.Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.flight.cost</code>.
	 */
	public java.lang.Long getCost() {
		return (java.lang.Long) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return tech.codingclub.helix.tables.Flight.FLIGHT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return tech.codingclub.helix.tables.Flight.FLIGHT.FROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return tech.codingclub.helix.tables.Flight.FLIGHT.TO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return tech.codingclub.helix.tables.Flight.FLIGHT.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field5() {
		return tech.codingclub.helix.tables.Flight.FLIGHT.COST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value5() {
		return getCost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FlightRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FlightRecord value2(java.lang.String value) {
		setFrom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FlightRecord value3(java.lang.String value) {
		setTo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FlightRecord value4(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FlightRecord value5(java.lang.Long value) {
		setCost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FlightRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.Long value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FlightRecord
	 */
	public FlightRecord() {
		super(tech.codingclub.helix.tables.Flight.FLIGHT);
	}

	/**
	 * Create a detached, initialised FlightRecord
	 */
	public FlightRecord(java.lang.Long id, java.lang.String from, java.lang.String to, java.lang.String name, java.lang.Long cost) {
		super(tech.codingclub.helix.tables.Flight.FLIGHT);

		setValue(0, id);
		setValue(1, from);
		setValue(2, to);
		setValue(3, name);
		setValue(4, cost);
	}
}
