/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PassengerRecord extends org.jooq.impl.UpdatableRecordImpl<tech.codingclub.helix.tables.records.PassengerRecord> implements org.jooq.Record7<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = -359682625;

	/**
	 * Setter for <code>public.passenger.passenger_id</code>.
	 */
	public void setPassengerId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.passenger.passenger_id</code>.
	 */
	public java.lang.Long getPassengerId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.passenger.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.passenger.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.passenger.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.passenger.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.passenger.phone</code>.
	 */
	public void setPhone(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.passenger.phone</code>.
	 */
	public java.lang.String getPhone() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.passenger.date</code>.
	 */
	public void setDate(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.passenger.date</code>.
	 */
	public java.lang.String getDate() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.passenger.member_id</code>.
	 */
	public void setMemberId(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.passenger.member_id</code>.
	 */
	public java.lang.Long getMemberId() {
		return (java.lang.Long) getValue(5);
	}

	/**
	 * Setter for <code>public.passenger.flight_id</code>.
	 */
	public void setFlightId(java.lang.Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.passenger.flight_id</code>.
	 */
	public java.lang.Long getFlightId() {
		return (java.lang.Long) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return tech.codingclub.helix.tables.Passenger.PASSENGER.PASSENGER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return tech.codingclub.helix.tables.Passenger.PASSENGER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return tech.codingclub.helix.tables.Passenger.PASSENGER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return tech.codingclub.helix.tables.Passenger.PASSENGER.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return tech.codingclub.helix.tables.Passenger.PASSENGER.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return tech.codingclub.helix.tables.Passenger.PASSENGER.MEMBER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field7() {
		return tech.codingclub.helix.tables.Passenger.PASSENGER.FLIGHT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getPassengerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getMemberId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value7() {
		return getFlightId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PassengerRecord value1(java.lang.Long value) {
		setPassengerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PassengerRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PassengerRecord value3(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PassengerRecord value4(java.lang.String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PassengerRecord value5(java.lang.String value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PassengerRecord value6(java.lang.Long value) {
		setMemberId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PassengerRecord value7(java.lang.Long value) {
		setFlightId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PassengerRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.Long value6, java.lang.Long value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PassengerRecord
	 */
	public PassengerRecord() {
		super(tech.codingclub.helix.tables.Passenger.PASSENGER);
	}

	/**
	 * Create a detached, initialised PassengerRecord
	 */
	public PassengerRecord(java.lang.Long passengerId, java.lang.String name, java.lang.String email, java.lang.String phone, java.lang.String date, java.lang.Long memberId, java.lang.Long flightId) {
		super(tech.codingclub.helix.tables.Passenger.PASSENGER);

		setValue(0, passengerId);
		setValue(1, name);
		setValue(2, email);
		setValue(3, phone);
		setValue(4, date);
		setValue(5, memberId);
		setValue(6, flightId);
	}
}
