/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Passenger extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.PassengerRecord> {

	private static final long serialVersionUID = 1047466695;

	/**
	 * The singleton instance of <code>public.passenger</code>
	 */
	public static final tech.codingclub.helix.tables.Passenger PASSENGER = new tech.codingclub.helix.tables.Passenger();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.PassengerRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.PassengerRecord.class;
	}

	/**
	 * The column <code>public.passenger.passenger_id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.PassengerRecord, java.lang.Long> PASSENGER_ID = createField("passenger_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.passenger.name</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.PassengerRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.passenger.email</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.PassengerRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.passenger.phone</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.PassengerRecord, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.passenger.date</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.PassengerRecord, java.lang.String> DATE = createField("date", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.passenger.member_id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.PassengerRecord, java.lang.Long> MEMBER_ID = createField("member_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.passenger.flight_id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.PassengerRecord, java.lang.Long> FLIGHT_ID = createField("flight_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.passenger</code> table reference
	 */
	public Passenger() {
		this("passenger", null);
	}

	/**
	 * Create an aliased <code>public.passenger</code> table reference
	 */
	public Passenger(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Passenger.PASSENGER);
	}

	private Passenger(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.PassengerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Passenger(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.PassengerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<tech.codingclub.helix.tables.records.PassengerRecord, java.lang.Long> getIdentity() {
		return tech.codingclub.helix.Keys.IDENTITY_PASSENGER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<tech.codingclub.helix.tables.records.PassengerRecord> getPrimaryKey() {
		return tech.codingclub.helix.Keys.PASSENGER_PRIMARYKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.PassengerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<tech.codingclub.helix.tables.records.PassengerRecord>>asList(tech.codingclub.helix.Keys.PASSENGER_PRIMARYKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Passenger as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Passenger(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Passenger rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Passenger(name, null);
	}
}
